name="Dev"
num=25
height=5.8
is_student=True
fruits=["apple","mango","pineapple"]
colors=("white","green","pink")
print(name)
print(type(name))
print(num)
print(type(num))
print(height)
print(type(height))
print(is_student)
print(type(is_student))
print(fruits)
print(type(fruits))
print(colors)
print(type(colors))